/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author lucasbrautigam
 */
public class AktuellaOrdrar extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AktuellaOrdrar.class.getName());

    /**
     * Creates new form AktuellaOrdrar
     */
    public AktuellaOrdrar(InfDB idb) {
        this.idb = idb;
        initComponents();
        
        fyllOrderTabell();
    }
    
    private void fyllOrderTabell(){
        try {
            String sql = "SELECT * FROM Ordrar WHERE Status != 'Klar'";
            
            ArrayList<HashMap<String, String>> allaOrdrar = idb.fetchRows(sql);
            
            DefaultTableModel model = (DefaultTableModel)jtAktuellaOrdrar.getModel();
            model.setRowCount(0);
            
            if(allaOrdrar != null) {
                for(HashMap<String, String> rad : allaOrdrar) {
                model.addRow(new Object[]{
                    rad.get("OrderID"),
                    rad.get("KundID"),
                    rad.get("OrderDatum"),
                    rad.get("Status"),
                    rad.get("ArSnabborder"),
                    rad.get("FraktAdress"),
                    rad.get("TotalPrisInclMoms")
                });
            }
            }
        }catch(InfException ex) {
            JOptionPane.showMessageDialog(null, "Kunde inte hämta ordrar: "+ ex.getMessage());
        }
        
        
jtAktuellaOrdrar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);



jtAktuellaOrdrar.getColumnModel().getColumn(0).setPreferredWidth(100);  
jtAktuellaOrdrar.getColumnModel().getColumn(1).setPreferredWidth(100);  
jtAktuellaOrdrar.getColumnModel().getColumn(2).setPreferredWidth(250); 
jtAktuellaOrdrar.getColumnModel().getColumn(3).setPreferredWidth(200);
jtAktuellaOrdrar.getColumnModel().getColumn(4).setPreferredWidth(150);  
jtAktuellaOrdrar.getColumnModel().getColumn(5).setPreferredWidth(300); 
jtAktuellaOrdrar.getColumnModel().getColumn(6).setPreferredWidth(150); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtAktuellaOrdrar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtAktuellaOrdrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "KundID", "OrderDatum", "Status", "ArSnabborder", "FraktAdress", "TotalPrisInclMoms"
            }
        ));
        jScrollPane2.setViewportView(jtAktuellaOrdrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AktuellaOrdrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtAktuellaOrdrar;
    // End of variables declaration//GEN-END:variables
}
