package hattmakaren2026_9;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ziggy
 */
import oru.inf.InfDB;
import oru.inf.InfException;

import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Kundsida extends javax.swing.JFrame {
    private InfDB db;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kundsida.class.getName());
    /**
     * Creates new form Kundsida
     */
    public Kundsida() {
        initComponents();
        try {
        String dbPath = "C:\\db\\HOGDB.FDB";   // ÄNDRA till din sökväg
        db = new InfDB(dbPath);
    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Kunde inte ansluta till databasen!");
    }
    }
    
    public void visaAllaKunder() {
        
// Rensa tabellen först
    ((DefaultTableModel) TBLkund.getModel()).setRowCount(0);

    try {
        String sql = "SELECT KundID, namn, epost, Telefon, Adress FROM Users";
        
        ArrayList<HashMap<String, String>> resultat = db.fetchRows(sql);

        // Kolla om det kom tillbaka några resultat
        if (resultat == null || resultat.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Det finns inga kunder i databasen",
                "Inga kunder", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Lägg till raderna i tabellen
        for (HashMap<String, String> rad : resultat) {
            Object[] row = {
                rad.get("KUNDID"),
                rad.get("NAMN"),
                rad.get("EPOST"),
                rad.get("TELEFON"),
                rad.get("ADRESS")
            };
            ((DefaultTableModel) TBLkund.getModel()).addRow(row);
        }

    } catch (InfException e) {
        JOptionPane.showMessageDialog(this,
            "Fel vid hämtning av kunder:\n" + e.getMessage(),
            "Databasfel", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    
    public void sokKunder(String sokText) {
    
        // Rensa tabellen
        ((DefaultTableModel) TBLkund.getModel()).setRowCount(0);

        // Om sökfältet är tomt → visa alla kunder istället
        if (sokText == null || sokText.trim().isEmpty()) {
            visaAllaKunder();
            return;
        }

        try {
            // Använd LIKE direkt i SQL-strängen (InfDB gillar detta bättre)
            String sql = "SELECT KundID, namn, epost, Telefon, Adress " +
                         "FROM Users WHERE namn LIKE '%" + sokText.trim() + "%'";

            // Här skickar vi INGEN extra parameter
            ArrayList<HashMap<String, String>> resultat = db.fetchRows(sql);

            if (resultat == null || resultat.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Inga kunder hittades som matchar: " + sokText,
                    "Inga resultat", 
                    JOptionPane.INFORMATION_MESSAGE);
                return;
        }

            // Fyll tabellen med resultaten
            for (HashMap<String, String> rad : resultat) {
                Object[] row = {
                    rad.get("KUNDID"),
                    rad.get("NAMN"),
                    rad.get("EPOST"),
                    rad.get("TELEFON"),
                    rad.get("ADRESS")
                };
                ((DefaultTableModel) TBLkund.getModel()).addRow(row);
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this,
                "Fel vid sökning:\n" + e.getMessage(),
                "Databasfel", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNmeny = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLkund = new javax.swing.JTable();
        TXTsokfunktion = new javax.swing.JTextField();
        TXThantera = new javax.swing.JButton();
        CBOXsortera = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNmeny.setText("Meny");
        BTNmeny.addActionListener(this::BTNmenyActionPerformed);

        TBLkund.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kund ID", "Namn", "Epost", "Telefon", "Adress"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLkund);

        TXTsokfunktion.setText("Sök...");
        TXTsokfunktion.addActionListener(this::TXTsokfunktionActionPerformed);
        TXTsokfunktion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTsokfunktionKeyPressed(evt);
            }
        });

        TXThantera.setText("Hantera");

        CBOXsortera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortera...", "Stigande", "Fallande", "Alfabetiskt" }));
        CBOXsortera.addActionListener(this::CBOXsorteraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TXTsokfunktion, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                        .addComponent(TXThantera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNmeny))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBOXsortera, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNmeny)
                        .addComponent(TXThantera))
                    .addComponent(TXTsokfunktion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(CBOXsortera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmenyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNmenyActionPerformed

    private void TXTsokfunktionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTsokfunktionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTsokfunktionActionPerformed

    private void CBOXsorteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOXsorteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOXsorteraActionPerformed

    private void TXTsokfunktionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTsokfunktionKeyPressed
        
    }//GEN-LAST:event_TXTsokfunktionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kundsida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNmeny;
    private javax.swing.JComboBox<String> CBOXsortera;
    private javax.swing.JTable TBLkund;
    private javax.swing.JButton TXThantera;
    private javax.swing.JTextField TXTsokfunktion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
