/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;
/**
 *
 * @author simon
 */
public class MaterialBestallningsSidan extends javax.swing.JFrame {
    private InfDB idb;

    
    private DefaultTableModel materialModel;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaterialBestallningsSidan.class.getName());

    /**
     * Creates new form MaterialBestallningsSidan
     */
    public MaterialBestallningsSidan(InfDB idb)throws InfException {
        this.idb = idb;
        initComponents();
        initMaterialTabell();
       laddaHelaTabellen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnSkapaPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMaterial);

        btnSkapaPdf.setText("Beställ material");
        btnSkapaPdf.addActionListener(this::btnSkapaPdfActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSkapaPdf)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSkapaPdf)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laddaHelaTabellen() {
        try {
            String sqlOrdrar = "SELECT OrderID FROM Ordrar WHERE Status IN ('Registrerad', 'Tillverkning')";
            ArrayList<HashMap<String, String>> aktivaOrdrar = idb.fetchRows(sqlOrdrar);

            if (aktivaOrdrar == null || aktivaOrdrar.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Det finns inga aktiva ordrar att beställa material till just nu.");
                return;
            }

            List<Integer> orderIds = new ArrayList<>();
            for (HashMap<String, String> order : aktivaOrdrar) {
                orderIds.add(Integer.parseInt(order.get("OrderID")));
            }

            List<HashMap<String, String>> resultatLista = hamtaMaterialbehov(orderIds);

            materialModel.setRowCount(0); 

            if (resultatLista != null && !resultatLista.isEmpty()) {
                for (HashMap<String, String> rad : resultatLista) {
                    int orderId = Integer.parseInt(rad.get("OrderID"));
                    
                    String material = rad.get("Namn"); 
                    
                    double behov = Double.parseDouble(rad.get("TotaltBehov"));
                    double saldo = Double.parseDouble(rad.get("LagerSaldo"));
                    
                    double bestall = Math.max(0.0, behov - saldo);

                    materialModel.addRow(new Object[]{orderId, material, behov, saldo, bestall});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inget materialbehov hittades för de aktiva ordrarna.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ett fel uppstod när tabellen skulle laddas: " + e.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void exporteraMaterialbestallning(List<MaterialRad> bestallning) {
    String datum = java.time.LocalDate.now().toString();
    String filnamn = "Materialbestallning_" + datum + ".txt";

    try (java.io.PrintWriter writer = new java.io.PrintWriter(filnamn, "UTF-8")) {
        writer.println("======= MATERIALBESTÄLLNING =======");
        writer.println("Datum: " + java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
        writer.println("-----------------------------------");

        double totaltAntalEnheter = 0;

        for (MaterialRad rad : bestallning) {
            writer.println("Material:  " + rad.material);
            writer.println("Antal:     " + rad.bestall);
            writer.println("-----------------------------------");
            totaltAntalEnheter += rad.bestall;
        }

        writer.println("Totalt antal enheter: " + totaltAntalEnheter);
        writer.println("===================================");
        writer.println("Beställning skapad av systemet.");

        javax.swing.JOptionPane.showMessageDialog(this, "Success! Beställningsfil skapad: " + filnamn);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid export: " + e.getMessage());
    }
}
    private void initMaterialTabell() {
        materialModel = new DefaultTableModel(
                new Object[]{"Kundorder", "Material", "Antal material", "Lagersaldo", "Behöver beställas", "Beställ?"},
                0
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 5) return Boolean.class; 
                return super.getColumnClass(columnIndex);
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4 || column == 5; 
            }
        };
        tblMaterial.setModel(materialModel);
    }
    private List<HashMap<String, String>> hamtaMaterialbehov(List<Integer> orderIds) throws InfException {

        String ids = orderIds.stream()
                .map(String::valueOf)
                .collect(Collectors.joining(", "));

        String sql =
                "SELECT o.OrderID, m.Namn, " +
                        "SUM(r.Antal * hm.Antal) AS TotaltBehov, " +
                        "m.LagerSaldo " +
                        "FROM Ordrar o " +
                        "JOIN Orderrader r ON o.OrderID = r.OrderID " +
                        "JOIN Hatt_Material hm ON r.ModellID = hm.ModellID " +
                        "JOIN Material m ON hm.MaterialID = m.MaterialID " +
                        "WHERE o.OrderID IN (" + ids + ") " +
                        "GROUP BY o.OrderID, m.MaterialID, m.Namn, m.LagerSaldo;";

        return idb.fetchRows(sql);
    }
    
    private void btnSkapaPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaPdfActionPerformed
        if (tblMaterial.isEditing()) {
            tblMaterial.getCellEditor().stopCellEditing();
        }
        List<MaterialRad> bestallning = hamtaBestallningsrader();

        if (bestallning.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Du måste kryssa i 'Beställ?' på minst ett material och ange ett antal över 0.");
            return;
        }
        StringBuilder kvitto = new StringBuilder("Följande material kommer beställas och läggas till i lagret:\n\n");
        for(MaterialRad rad : bestallning) {
            kvitto.append("- ").append(rad.material).append(" - Antal: ").append(rad.bestall).append("\n");
        }
        kvitto.append("\nVill du genomföra beställningen, och skapa en textfil?");

        int svar = JOptionPane.showConfirmDialog(this, kvitto.toString(), "Bekräfta beställning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (svar == JOptionPane.YES_OPTION) {
            try {
                for(MaterialRad rad : bestallning) {
                    String sqlUpdate = "UPDATE Material SET LagerSaldo = LagerSaldo + " + rad.bestall + " WHERE Namn = '" + rad.material + "'";
                    idb.update(sqlUpdate);
                }
                                exporteraMaterialbestallning(bestallning);
                JOptionPane.showMessageDialog(this, "Lagret är nu påfyllt i databasen!", "Succé", JOptionPane.INFORMATION_MESSAGE);
                
                laddaHelaTabellen();
                
            } catch (InfException e) {
                JOptionPane.showMessageDialog(this, "Ett fel uppstod när lagret skulle uppdateras: " + e.getMessage(), "Databasfel", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private List<MaterialRad> hamtaBestallningsrader() {
        List<MaterialRad> lista = new ArrayList<>();

        for (int i = 0; i < materialModel.getRowCount(); i++) {
            boolean villBestalla = false;
            Object checkbox = materialModel.getValueAt(i, 5);
            if (checkbox != null) {
                villBestalla = (boolean) checkbox;
            }

            if (villBestalla) {
                int orderId = Integer.parseInt(materialModel.getValueAt(i, 0).toString());
                String material = materialModel.getValueAt(i, 1).toString();
                
                double behov = Double.parseDouble(materialModel.getValueAt(i, 2).toString());
                double saldo = Double.parseDouble(materialModel.getValueAt(i, 3).toString());
                double bestall = Double.parseDouble(materialModel.getValueAt(i, 4).toString());

                if (bestall > 0) {
                    lista.add(new MaterialRad(orderId, material, behov, saldo, bestall));
                }
            }
        }

        return lista;
    }

    public static class MaterialRad {
        public int orderId;
        public String material;
        public double behov;   
        public double saldo;   
        public double bestall; 

        public MaterialRad(int orderId, String material, double behov, double saldo, double bestall) {
            this.orderId = orderId;
            this.material = material;
            this.behov = behov;
            this.saldo = saldo;
            this.bestall = bestall;
        }
    }//GEN-LAST:event_btnSkapaPdfActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaPdf;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMaterial;
    // End of variables declaration//GEN-END:variables
}
