/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.ArrayList;

/**
 *
 * @author Linus
 */
public class OrderHistorik extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderHistorik.class.getName());
    private InfDB idb;
        
    /**
     * Creates new form OrderHistorik
     */
    public OrderHistorik(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        fyllRullListaMedKunder();
    }
    
    private void fyllRullListaMedKunder() {
        try {
            ArrayList<String> namnLista = idb.fetchColumn("select namn from kunder");
            
            if (namnLista != null) {
                for (String namn : namnLista) {
                    cmbKunder.addItem(namn);
                }
            }
        } catch (InfException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrderHistorikRubrik = new javax.swing.JLabel();
        cmbKunder = new javax.swing.JComboBox<>();
        btnVisaHistorik = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorikText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOrderHistorikRubrik.setText("Orderhistorik");

        cmbKunder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVisaHistorik.setText("Visa historik");

        txtHistorikText.setColumns(20);
        txtHistorikText.setRows(5);
        jScrollPane1.setViewportView(txtHistorikText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cmbKunder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisaHistorik)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOrderHistorikRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblOrderHistorikRubrik)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbKunder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVisaHistorik))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisaHistorik;
    private javax.swing.JComboBox<String> cmbKunder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderHistorikRubrik;
    private javax.swing.JTextArea txtHistorikText;
    // End of variables declaration//GEN-END:variables
}
