/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;


/**
 *
 * @author alexanderbohm
 */
public class RegistreraKunder extends javax.swing.JFrame {
    private InfDB idb;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistreraKunder.class.getName());

    /**
     * Creates new form RegistreraKunder
     */
    public RegistreraKunder(InfDB idb) {
        this.idb = idb;
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefonnummer = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtMejladress = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        btnRegNyKund = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSokKund = new javax.swing.JLabel();
        tftSokFramKund = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTelefonnummer.setText("Telefonnummer");
        txtTelefonnummer.addActionListener(this::txtTelefonnummerActionPerformed);

        txtNamn.setText("Namn");

        txtMejladress.setText("Mejladress");

        txtAdress.setText("Adress");

        btnRegNyKund.setText("Registrera ny kund");
        btnRegNyKund.addActionListener(this::btnRegNyKundActionPerformed);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        jLabel1.setText("Telefonnummer");

        jLabel2.setText("Namn");

        jLabel3.setText("Mejl");

        jLabel4.setText("Adress");

        lblSokKund.setText("Sök fram kund");

        tftSokFramKund.addActionListener(this::tftSokFramKundActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblSokKund))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamn)
                                    .addComponent(txtMejladress, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(txtAdress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegNyKund))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tftSokFramKund, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSpara)
                                .addGap(27, 27, 27)
                                .addComponent(btnTaBort)))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokKund)
                    .addComponent(tftSokFramKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegNyKund))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMejladress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTaBort))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    try {
        String sokID = tftSokFramKund.getText(); // Vi utgår från ID:t vi sökte på
        
        String sql = "UPDATE Kunder SET "
                     + "Namn = '" + txtNamn.getText() + "', "
                     + "Adress = '" + txtAdress.getText() + "', "
                     + "Epost = '" + txtMejladress.getText() + "', "
                     + "Telefon = '" + txtTelefonnummer.getText() + "' "
                     + "WHERE KundID = " + sokID;
        
        idb.update(sql);
        JOptionPane.showMessageDialog(null, "Kunduppgifter har uppdaterats!");
        
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Kunde inte uppdatera. Kontrollera att KundID i sökrutan är korrekt.");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaActionPerformed

    private void txtTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonnummerActionPerformed

    private void tftSokFramKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftSokFramKundActionPerformed
    try {
        String sokVarde = tftSokFramKund.getText().trim();         // Hämtar det användaren skrev
        
        if (sokVarde.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen skriv in ett KundID eller Namn för att söka.");
            return;
        }
        
        String sql = "SELECT * FROM Kunder WHERE KundID = '" + sokVarde + "' OR Namn LIKE '%" + sokVarde + "%'";
        
        HashMap<String, String> kundData = idb.fetchRow(sql);
        
        if (kundData != null) {
            // Om kunden hittas, fyll i de andra rutorna
            txtNamn.setText(kundData.get("Namn"));
            txtTelefonnummer.setText(kundData.get("Telefon"));
            txtMejladress.setText(kundData.get("Epost"));
            txtAdress.setText(kundData.get("Adress"));
        } else {
            JOptionPane.showMessageDialog(null, "Kunden '" + sokVarde + "' hittades inte.");
        }
        
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Ett fel uppstod vid sökning!");
        System.out.println(ex.getMessage());
    }
    }//GEN-LAST:event_tftSokFramKundActionPerformed

    private void btnRegNyKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNyKundActionPerformed
    try {
        String namn = txtNamn.getText().trim();
        String mejladress = txtMejladress.getText().trim();
        String telefon = txtTelefonnummer.getText().trim();
        String adress = txtAdress.getText().trim();
               
       if (namn.isEmpty() || adress.isEmpty() || mejladress.isEmpty() || telefon.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Alla fält måste fyllas i!");
       }
       
       String sql = "INSERT INTO Kunder (Namn, Adress, Telefon, Epost) VALUES ('" 
        + namn + "', '" 
        + adress + "', '" 
        + telefon + "', '" 
        + mejladress + "')";
       
       
       idb.insert(sql);
       JOptionPane.showMessageDialog(null, "Ny kund har registrerats!");
       
       txtNamn.setText(""); txtAdress.setText(""); txtMejladress.setText(""); txtTelefonnummer.setText("");
       
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Gick inte att spara i databasen. Kontrollera uppgifterna.");
    }
    }//GEN-LAST:event_btnRegNyKundActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
 // Fråga först om de är säkra
    int svar = JOptionPane.showConfirmDialog(null, "Är du helt säker på att du vill ta bort kunden?", "Ta bort kund", JOptionPane.YES_NO_OPTION);
    
    if (svar == JOptionPane.YES_OPTION) {
        try {
            String sokID = tftSokFramKund.getText();
            String sql = "DELETE FROM Kunder WHERE KundID = " + sokID;
            
            idb.delete(sql);
            JOptionPane.showMessageDialog(null, "Kunden har raderats.");
            
            // Rensa fälten efter radering
            txtNamn.setText(""); txtAdress.setText(""); txtMejladress.setText(""); txtTelefonnummer.setText(""); tftSokFramKund.setText("");
            
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Kunde inte ta bort kunden. Den kan vara kopplad till en order.");
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegNyKund;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSokKund;
    private javax.swing.JTextField tftSokFramKund;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtMejladress;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
