/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;


/**
 *
 * @author alexanderbohm
 */
public class RegistreraKunder extends javax.swing.JFrame {
    private InfDB idb;
    private int KundID;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistreraKunder.class.getName());

    /**
     * Creates new form RegistreraKunder
     */
    public RegistreraKunder(InfDB idb, int KundID) {
        this.idb = idb;
        this.KundID = KundID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefonnummer = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtMejladress = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        btnRegNyKund = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSokKund = new javax.swing.JLabel();
        tftSokFramKund = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTelefonnummer.setText("Telefonnummer");
        txtTelefonnummer.addActionListener(this::txtTelefonnummerActionPerformed);

        txtNamn.setText("Namn");

        txtMejladress.setText("Mejladress");

        txtAdress.setText("Adress");

        btnRegNyKund.setText("Registrera ny kund");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        btnTaBort.setText("Ta bort");

        jLabel1.setText("Telefonnummer");

        jLabel2.setText("Namn");

        jLabel3.setText("Mejl");

        jLabel4.setText("Adress");

        lblSokKund.setText("Sök fram kund");

        tftSokFramKund.addActionListener(this::tftSokFramKundActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblSokKund))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamn)
                                    .addComponent(txtMejladress, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(txtAdress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegNyKund))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tftSokFramKund, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSpara)
                                .addGap(27, 27, 27)
                                .addComponent(btnTaBort)))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokKund)
                    .addComponent(tftSokFramKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegNyKund))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMejladress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTaBort))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaActionPerformed

    private void txtTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonnummerActionPerformed

    private void tftSokFramKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftSokFramKundActionPerformed
    try {
        String sokVarde = tftSokFramKund.getText().trim();         // Hämtar det användaren skrev
        
        if (sokVarde.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen skriv in ett KundID eller Namn för att söka.");
            return;
        }
        
        String sql = "SELECT * FROM Kunder WHERE KundID = '" + sokVarde + "' OR Namn LIKE '%" + sokVarde + "%'";
        
        HashMap<String, String> kundData = idb.fetchRow(sql);
        
        if (kundData != null) {
            // Om kunden hittas, fyll i de andra rutorna
            txtNamn.setText(kundData.get("Namn"));
            txtTelefonnummer.setText(kundData.get("Telefon"));
            txtMejladress.setText(kundData.get("Epost"));
            txtAdress.setText(kundData.get("Epost"));
        } else {
            JOptionPane.showMessageDialog(null, "Kunden '" + sokVarde + "' hittades inte.");
        }
        
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(null, "Ett fel uppstod vid sökning!");
        System.out.println(ex.getMessage());
    }
    }//GEN-LAST:event_tftSokFramKundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new RegistreraKunder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegNyKund;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSokKund;
    private javax.swing.JTextField tftSokFramKund;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtMejladress;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
