
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakaren2026_9;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


    
    /**
     * Creates new form SkapaKundorder
     */
public class SkapaKundorder extends javax.swing.JFrame {

    // 1. Flytta upp din inner class hit så den är lätt att hitta
    public class KundItem {
        int id;
        String namn;

        public KundItem(int id, String namn) {
            this.id = id;
            this.namn = namn;
        }

        @Override
        public String toString() {
            return namn; // Gör att bara namnet syns i listan
        }
    }

    public SkapaKundorder() {
        initComponents();
        loadComboData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnValjKund = new javax.swing.JButton();
        btnPaborjaOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skapa Kundorder");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kurt Lupton", "Mikael Maskerad", "Lotta Larsson", "Sofia Sömmerska", "Erik Export" }));

        btnValjKund.setText("Välj");
        btnValjKund.addActionListener(this::btnValjKundActionPerformed);

        btnPaborjaOrder.setText("Påbörja Order");
        btnPaborjaOrder.addActionListener(this::btnPaborjaOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPaborjaOrder)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnValjKund)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnValjKund))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnPaborjaOrder)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
/**
 * @author carlbrandstrom
 */
                       
    private void btnValjKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjKundActionPerformed
         Object valt = jComboBox1.getSelectedItem();
        if (valt != null) {
            System.out.println("Du valde: " + valt.toString());
    }//GEN-LAST:event_btnValjKundActionPerformed
    }
    private void btnPaborjaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaborjaOrderActionPerformed
       try {
            Object item = jComboBox1.getSelectedItem();
            if (!(item instanceof KundItem)) {
                JOptionPane.showMessageDialog(this, "Välj en giltig kund först!");
                return;
           
    }//GEN-LAST:event_btnPaborjaOrderActionPerformed


            KundItem valdKund = (KundItem) item;
            int kundID = valdKund.id;

            // Använd samma uppkoppling som i loadComboData om du inte har en DatabaseConnection-klass
            String url = "jdbc:mysql://localhost:3306/hattmakaren?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "Nikko22b");

            String sql = "INSERT INTO ordrar (KundID, OrderDatum) VALUES (?, NOW())";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, kundID);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Order skapad för kund ID: " + kundID);

            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kunde inte skapa order: " + e.getMessage());
            e.printStackTrace();
        }    
    }
    public void loadComboData() {
        try {
            jComboBox1.removeAllItems();
            String url = "jdbc:mysql://localhost:3306/hattmakaren?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection conn = DriverManager.getConnection(url, "root", "Nikko22b");

            String sql = "SELECT namn, kundID FROM Kunder";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("kundID");
                String namn = rs.getString("namn");
                // FIX: Ta bort "int" och "String" inuti parentesen
                jComboBox1.addItem(new KundItem(id, namn));
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Databasfel: " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
            new SkapaKundorder().setVisible(true);
           }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaborjaOrder;
    private javax.swing.JButton btnValjKund;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}